version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remote-mcp-server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MCP_ENDPOINT=/mcp
      - ENABLE_LEGACY_TRANSPORT=true
      - LOG_LEVEL=info  # info = Basic logs, debug = Detailed server logs dump
    restart: unless-stopped
    networks:
      - mcp-network
    volumes:
      - ./logs:/app/logs

networks:
  mcp-network:
    driver: bridge